### ISSUE TITLE
Broken link for get started now button

### ISSUE THREAD

**Issue by Sagar2366** [PecanProject/pecan-documentation#7]
I noticed that link is broken for Get started now button on main page which redirects to http://pecan.ncsa.illinois.edu/pecan 

Not Found
The requested URL was not found on this server.

**Comment by vikasgrewal16** [comment]
can you assign this issue to me and guide me a little bit more about this issue how can i solve this?

**Comment by dlebauer** [comment]
@Sagar2366 thank you for reporting this. However, it is not clear where this issue occurred. The new base URL would be https://pecan-dev.ncsa.cloud/, but /pecan does not exist, and I can not find the string "Get started now" in the PEcAn github repository. Closing
